### ISSUE TITLE
.well-known not being created

### ISSUE THREAD

**Issue by developius** [voorhoede-labs/nuxt-twa-module#11]
**Describe the bug**
When running `npm run generate`, I'm not seeing a .well-known directory being created in `dist`. This is where I'd expect it to be, so that it can deployed to the server.

**To Reproduce**
1. Run `npm run generate`
2. No `.well-known` is created

**Expected behavior**
I would expect the `.well-known` directory to be created within `dist`.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser Chrome
 - Version 75

**Smartphone (please complete the following information):**
 - Device: Pixel 3 (via Android Studio AVD)
 - OS: Android 9
 - Browser Chrome
 - Version 74

**Additional context**
I think it would be worth improving the docs/publishing an example app to reference. For instance, it's not clear what we need to put in the `sha256Fingerprints` option in `nuxt.config.js`. The tests show a string, the docs use an array, but I've only got one SHA-256 from the keystore like this:

```
AC:98:0B:43 // etc - 32 pairs of chars/numbers, separated by a colon
```

Very happy to write docs/tutorials once I fully understand how it all works 😄 

I am also seeing lots of warnings in the console (see below).

<img width="652" alt="Screenshot 2019-07-22 16 27 27" src="https://user-images.githubusercontent.com/5836587/61606287-a9cae480-ac9d-11e9-9519-533e21256dc6.png">

**Comment by developius** [comment]
**Update**

This can be fixed by specifying `distFolder` in the nuxt config:
```js
modules: [
  ['nuxt-twa-module', {
    // snip
    distFolder: '/.nuxt/dist/client',
    // snip
  }
]
```

There appears to be an issue with the code that generates the output path.
When `distFolder` in nuxt config is left empty, [index.js:25](https://github.com/voorhoede/nuxt-twa-module/blob/master/index.js#L25) generates this path (note the lack of trailing slash after the project directory):

```
/Users/finnian/Documents/GitLab/sandfly-map-web.nuxt/dist/client 
```

This is compounded by [index.js:77](https://github.com/voorhoede/nuxt-twa-module/blob/master/index.js#L77):

```js
generateAssetLinksFile(options, rootDir + options.distFolder)
```

This results in the path that is actually used in [`generateAssetLinksFile()`](https://github.com/voorhoede/nuxt-twa-module/blob/master/lib/generate-asset-links-file.js#L30):

```
/Users/finnian/Documents/GitLab/sandfly-map-web/Users/finnian/Documents/GitLab/sandfly-map-web.nuxt/dist/client/.well-known 
```

😆 

P.S. when the app is deployed to the web server, is `/_nuxt/.well-known/assetlinks.json` the correct path for that file? I thought `.well-known` was usually at the root. Ta

**Comment by celinekurpershoek** [comment]
@developius Thanks for creating an issue, we have been taking a loot at it and added your remarks to the readme. 

Regarding the `.well-known` folder; in our example its at `.nuxt/dist/client/.well-known` this is working for an application we have build. Could you let me know if you got it to work?

**Comment by SylvainBigonneau** [comment]
> P.S. when the app is deployed to the web server, is `/_nuxt/.well-known/assetlinks.json` the correct path for that file? I thought `.well-known` was usually at the root. Ta

I'm also wondering about this... it seems that it shouldn't work?
